# compare 3 inputs into EGRET:
# raw concentrations (multiple values/dat)
# time-normalized daily concentrations (pulled from NWISdv and subset)
# flow-normalized daily concentrations (calculated by load/Q from NWISdv)

# dv
plot(tp_wy_dv_out$Daily$ConcDay ~ tp_wy_dv_out$Daily$Date, 
     xlim = as.Date(c('2000-01-01', '2001-01-01')), type = 'l')

#fn dv
points(tp_wy_dv_fn_out$Daily$ConcDay ~ tp_wy_dv_fn_out$Daily$Date, 
     xlim = as.Date(c('2000-01-01', '2001-01-01')), type = 'l', col = 'blue')

# all samples
points(tp_wy_out$Daily$ConcDay ~ tp_wy_out$Daily$Date, 
       xlim = as.Date(c('2000-01-01', '2001-01-01')), type = 'l', col = 'red')

# values generated by gclas
config <- make('config', remake_file = '10_get_data.yml')
dat <- readNWISdv(siteNumbers = config$site_no, parameterCd = config$pcodes, startDate = config$start_date, endDate = config$end_date)
dat_load <- readNWISdv(siteNumbers = config$site_no, parameterCd = '91050', startDate = config$start_date, endDate = config$end_date)


points(dat$X_00665_00003 ~ dat$Date, 
       xlim = as.Date(c('2000-01-01', '2001-01-01')), type = 'l', col = 'green')

# merge data, calculate year sums for each method for flux
dat_dv <- tp_wy_dv_out$Daily %>%
  select(Date, FluxDay) %>%
  mutate(source = 'dv')

dat_dv_fn <- tp_wy_dv_fn_out$Daily %>%
  select(Date, FluxDay) %>%
  mutate(source = 'dv_fn')

dat_raw <- tp_wy_out$Daily %>%
  select(Date, FluxDay) %>%
  mutate(source = 'raw_conc')

dat_gclas <- dat_load %>%
  select(Date, FluxDay = X_91050_00003) %>%
  mutate(source = 'gclas') %>%
  mutate(FluxDay = FluxDay/2.205)

summary(dat_gclas$FluxDay)
summary(dat_raw$FluxDay)

plot(dat_gclas$FluxDay ~ dat_gclas$Date, type = 'l', xlim = as.Date(c('2000-01-01', '2001-01-01')))
points(dat_raw$FluxDay ~ dat_raw$Date, type = 'l', col = 'red')


all_flux <- bind_rows(dat_dv, dat_dv_fn, dat_raw, dat_gclas)
all_flux <- addWaterYear(all_flux)

annual_flux <- group_by(all_flux, source, waterYear) %>%
  summarize(annual_flux = sum(FluxDay, na.rm = T), 
            count = n()) %>%
  filter(waterYear != 1990)

cum_flux <- all_flux %>%
  arrange(source, Date) %>%
  filter(waterYear != 1990) %>%
  group_by(source) %>%
  mutate(cumulative_sum = cumsum(FluxDay)) %>%
  ungroup()

head(annual_flux)

p <- ggplot(annual_flux, aes(x = waterYear, y = annual_flux)) +
  geom_line(aes(color = source)) +
  geom_point(aes(color = source)) +
  theme_bw() +
  labs(x = "Water Year", y = "Annual Flux (kg)", color = 'Input data')

p2 <- ggplot(cum_flux, aes(x = Date, y = cumulative_sum)) +
  geom_line(aes(color = source, group = source)) +
  theme_bw() +
  labs(y = 'Cumulative Flux (kg)', color = 'Input data')

ggsave('figures/annual_load_method_compare.png', p, height = 6, width = 10)
ggsave('figures/cumulative_daily_load_method_compare.png', p2, height = 6, width = 10)
